# 보간할 이미지를 모아둔 폴더
input_folder : 'frames'
# 결과물을 모아둘 폴더
output_folder : 'frames_VFI'
# 모델 결정
model_type : 'SF_AdaCoF'
# 모델 학습 pth 결정  you can choose 50(just train with l1 loss) or 60(+10 train with gan loss)
checkpoint_number : '60'

# mp4_own과 url_path는 두개 전부 None이 아니어서는 안됨.
# 가지고 있는 영상을 보간하고 싶을 경우, 영상의 경로 설정
mp4_own : None
# 유튜브 영상을 보간하고 싶을 경우, 유튜브 영상의 링크
url_path : None
# 영상을 보간할 유튜브 영상 프레임 지정, 원본을 사용하고 싶다면 -1, 설정시 25이하 권장
frame : 30

# 보간의 반복 횟수 you can choose 1 or 2
# if you choose 1 you can get *2 frames counts and if you choose 2 you can get *4 frames counts
repeat : 1

# mp4 영상 저장 및 gif 형식 저장 유무 ( bool type )
mp4_save : True
gif_save : True